### ISSUE TITLE
ecbuild failure to detect netcdf-fortran when building standalone.

### ISSUE THREAD

**Issue by DJDavies2** [MetOffice/monio#41]
Ecbuild fails when building standalone:

CMake Error at /home/h01/frwd/cylc-run/mi-be984/share/installs/ecbuild/share/ecbuild/cmake/ecbuild_add_library.cmake:308 (add_library):
  Target "monio" links to target "NetCDF::NetCDF_Fortran" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  /home/h01/frwd/cylc-run/mi-be984/share/installs/ecbuild/share/ecbuild/cmake/ecbuild_add_library.cmake:667 (ecbuild_add_library_impl)
  src/CMakeLists.txt:59 (ecbuild_add_library)

**Comment by phlndrwd** [comment]
Thanks @DJDavies2. I'm not overly familiar with `CMake`, but I'm looking at MONIO now and seeing that there is no reference to `NetCDF::NetCDF_Fortran`. Because the library makes exclusive use of the NetCDF C++ library, there is _only_ a link to it. Please see: https://github.com/MetOffice/monio/blob/2c3e0318c5651f1269daee361c576e3001048156/src/CMakeLists.txt#L66.

Is it possible the standalone build is trying to link MONIO with a library it does not make explicit use of?

**Comment by DJDavies2** [comment]
Yes, there can be indirect usage of libraries that cmake attempts to resolve.  This should probably happen automatically but we see that it doesn't in many cases.  For instance monio depends on oops, which might depend on netcdf-fortran, so there might be a transitive dependency there.

There is a bug somewhere, but it isn't clear where (oops?  netcdf?  ecbuild?  cmake?).
